import type { PropertyCardData } from "../types/property";

export const MOCK_PROPERTIES: PropertyCardData[] = [
  {
    id: "1",
    slug: "apartment-shebin-luxury",
    title: "شقة سكنية فاخرة - تشطيب سوبر لوكس",
    location: "شبين الكوم، حي الجامعة",
    price: 2500000,
    image: "/images/stitch/prop_living_room.jpg",
    category: "شقة",
    transactionType: "sale",
    featured: true,
    rooms: 3,
    bathrooms: 2,
    area: 150,
  },
  {
    id: "2",
    slug: "office-shebin-downtown",
    title: "مقر إداري مجهز بالكامل",
    location: "شبين الكوم، شارع باريس",
    price: 15000,
    image: "/images/stitch/prop_office.jpg",
    category: "مكتب",
    transactionType: "rent",
    featured: false,
    rooms: 4,
    bathrooms: 2,
    area: 200,
  },
  {
    id: "3",
    slug: "villa-quweisna-garden",
    title: "فيلا مستقلة مع حديقة خاصة",
    location: "قويسنا، حي الفيلات",
    price: 5200000,
    image: "/images/stitch/prop_villa_garden.jpg",
    category: "فيلا",
    transactionType: "sale",
    featured: true,
    rooms: 5,
    bathrooms: 4,
    area: 350,
  },
  {
    id: "4",
    slug: "studio-cairo-new",
    title: "استوديو مودرن - القاهرة الجديدة",
    location: "القاهرة الجديدة، التجمع الخامس",
    price: 1200000,
    image: "/images/stitch/prop_living_room.jpg",
    category: "شقة",
    transactionType: "sale",
    featured: false,
    rooms: 1,
    bathrooms: 1,
    area: 65,
  },
  {
    id: "5",
    slug: "warehouse-october",
    title: "مستودع تجاري بمساحة كبيرة",
    location: "السادس من أكتوبر، المنطقة الصناعية",
    price: 25000,
    image: "/images/stitch/prop_office.jpg",
    category: "مستودع",
    transactionType: "rent",
    featured: false,
    rooms: 0,
    bathrooms: 2,
    area: 500,
  },
  {
    id: "6",
    slug: "penthouse-alex-royal",
    title: "بنتهاوس فاخر بإطلالة بحرية",
    location: "الإسكندرية، سيدي جابر",
    price: 8500000,
    image: "/images/stitch/prop_villa_garden.jpg",
    category: "بنتهاوس",
    transactionType: "sale",
    featured: true,
    rooms: 4,
    bathrooms: 3,
    area: 280,
  },
  {
    id: "7",
    slug: "apartment-cairo-manial",
    title: "شقة أنيقة بشارع رئيسي",
    location: "القاهرة، المعادي",
    price: 8000,
    image: "/images/stitch/prop_living_room.jpg",
    category: "شقة",
    transactionType: "rent",
    featured: false,
    rooms: 2,
    bathrooms: 1,
    area: 95,
  },
  {
    id: "8",
    slug: "villa-6october-modern",
    title: "فيلا حديثة بتصميم معماري عصري",
    location: "السادس من أكتوبر، الشيخ زايد",
    price: 7500000,
    image: "/images/stitch/prop_villa_garden.jpg",
    category: "فيلا",
    transactionType: "sale",
    featured: false,
    rooms: 6,
    bathrooms: 5,
    area: 450,
  },
  {
    id: "9",
    slug: "clinic-mansoura",
    title: "عيادة مجهزة بأحدث المعدات",
    location: "المنصورة، شارع الجيش",
    price: 12000,
    image: "/images/stitch/prop_office.jpg",
    category: "عيادة",
    transactionType: "rent",
    featured: false,
    rooms: 3,
    bathrooms: 2,
    area: 120,
  },
  {
    id: "10",
    slug: "apartment-tanta-modern",
    title: "شقة عائلية واسعة - تطل على شارع هادئ",
    location: "طن_tensors، شارع الحلو",
    price: 9000,
    image: "/images/stitch/prop_living_room.jpg",
    category: "شقة",
    transactionType: "rent",
    featured: false,
    rooms: 3,
    bathrooms: 2,
    area: 130,
  },
  {
    id: "11",
    slug: "shop-nasr-city",
    title: "محل تجاري بواجهة شارع رئيسي",
    location: "القاهرة، مدينة نصر",
    price: 18000,
    image: "/images/stitch/prop_office.jpg",
    category: "محل",
    transactionType: "rent",
    featured: false,
    rooms: 1,
    bathrooms: 1,
    area: 80,
  },
  {
    id: "12",
    slug: "villa-new-cairo-compound",
    title: "فيلا داخل كومبوند مغلق - أمن وخدمات",
    location: "القاهرة الجديدة، التجمع الخامس",
    price: 12000000,
    image: "/images/stitch/prop_villa_garden.jpg",
    category: "فيلا",
    transactionType: "sale",
    featured: true,
    rooms: 5,
    bathrooms: 4,
    area: 400,
  },
];

export const MOCK_TOTAL_PROPERTIES = 48;
export const MOCK_PAGE_SIZE = 9;

export function getMockProperties(page: number = 1): {
  properties: PropertyCardData[];
  total: number;
  totalPages: number;
} {
  const start = (page - 1) * MOCK_PAGE_SIZE;
  const properties = MOCK_PROPERTIES.slice(
    start % MOCK_PROPERTIES.length,
    (start % MOCK_PROPERTIES.length) + MOCK_PAGE_SIZE,
  ).map((p, i) => ({
    ...p,
    id: String(start + i + 1),
    slug: `${p.slug}-p${page}-${i}`,
  }));

  return {
    properties,
    total: MOCK_TOTAL_PROPERTIES,
    totalPages: Math.ceil(MOCK_TOTAL_PROPERTIES / MOCK_PAGE_SIZE),
  };
}
